# Funding options for AI Bradaa

# GitHub Sponsors
# github: [aibradaa-labs]

# Open Collective
# open_collective: aibradaa

# Ko-fi
# ko_fi: aibradaa

# Custom
custom: ["https://aibradaa.com/donate", "mailto:partnerships@aibradaa.com"]
