/**
 * Branding v1 Prototype
 * Badge, watermark, and branding utilities
 */

/**
 * Branding manager
 */
export class BrandingManager {
  constructor() {
    this.brandName = 'AI Bradaa';
    this.tagline = "Malaysia's AI Laptop Advisor";
    this.url = 'www.aibradaa.com';
    this.version = '1.0.0';
  }

  /**
   * Create 84-Mentor Council badge
   */
  createCouncilBadge() {
    const badge = document.createElement('div');
    badge.className = 'council-badge';
    badge.innerHTML = `
      <div class="badge-icon">84</div>
      <div class="badge-text">
        <div class="badge-title">Mentor Council</div>
        <div class="badge-subtitle">Verified</div>
      </div>
    `;
    return badge;
  }

  /**
   * Create tier badge
   */
  createTierBadge(tier) {
    const badge = document.createElement('span');
    badge.className = `tier-badge tier-badge-${tier}`;
    badge.textContent = tier.toUpperCase();
    return badge;
  }

  /**
   * Create powered by badge
   */
  createPoweredByBadge() {
    const badge = document.createElement('div');
    badge.className = 'powered-by-badge';
    badge.innerHTML = `
      <span class="badge-text">Powered by</span>
      <strong>${this.brandName}</strong>
    `;
    return badge;
  }

  /**
   * Create watermark for exports
   */
  createWatermark(type = 'subtle') {
    const watermark = document.createElement('div');
    watermark.className = `watermark watermark-${type}`;

    if (type === 'subtle') {
      watermark.innerHTML = `
        <span class="watermark-text">${this.brandName}</span>
      `;
    } else if (type === 'full') {
      watermark.innerHTML = `
        <div class="watermark-brand">${this.brandName}</div>
        <div class="watermark-tagline">${this.tagline}</div>
        <div class="watermark-url">${this.url}</div>
      `;
    }

    return watermark;
  }

  /**
   * Add watermark to text content
   */
  addTextWatermark(content, format = 'md') {
    const timestamp = new Date().toISOString();

    if (format === 'md' || format === 'markdown') {
      return `${content}\n\n---\n\n_Powered by ${this.brandName} • ${this.url}_\n_Generated: ${timestamp}_`;
    }

    if (format === 'html') {
      return `${content}\n<footer class="ai-bradaa-footer">\n  <p>Powered by <strong>${this.brandName}</strong> • <a href="https://${this.url}">${this.url}</a></p>\n  <p><small>Generated: ${timestamp}</small></p>\n</footer>`;
    }

    // Plain text
    return `${content}\n\n---\nPowered by ${this.brandName} • ${this.url}\nGenerated: ${timestamp}`;
  }

  /**
   * Create provenance trailer (for exports)
   */
  createProvenanceTrailer(metadata = {}) {
    const {
      model = 'gemini-2.0-flash-exp',
      sources = [],
      timestamp = new Date().toISOString(),
      tier = 'free',
      tokens = null,
    } = metadata;

    const trailer = {
      brand: this.brandName,
      url: this.url,
      version: this.version,
      model,
      sources,
      timestamp,
      tier,
      tokens,
    };

    return trailer;
  }

  /**
   * Format provenance trailer as text
   */
  formatProvenanceTrailer(trailer, format = 'md') {
    if (format === 'md' || format === 'markdown') {
      let md = '\n\n---\n\n## Provenance\n\n';
      md += `**Generated by:** ${trailer.brand}\n`;
      md += `**Website:** ${trailer.url}\n`;
      md += `**Model:** ${trailer.model}\n`;
      md += `**Timestamp:** ${trailer.timestamp}\n`;

      if (trailer.tokens) {
        md += `**Tokens Used:** ${trailer.tokens}\n`;
      }

      if (trailer.sources && trailer.sources.length > 0) {
        md += '\n**Sources:**\n';
        trailer.sources.forEach((source, i) => {
          md += `${i + 1}. [${source.title}](${source.url})\n`;
        });
      }

      return md;
    }

    if (format === 'json') {
      return JSON.stringify(trailer, null, 2);
    }

    // Plain text
    let text = '\n\n---\n\nPROVENANCE\n\n';
    text += `Generated by: ${trailer.brand}\n`;
    text += `Website: ${trailer.url}\n`;
    text += `Model: ${trailer.model}\n`;
    text += `Timestamp: ${trailer.timestamp}\n`;

    if (trailer.tokens) {
      text += `Tokens Used: ${trailer.tokens}\n`;
    }

    if (trailer.sources && trailer.sources.length > 0) {
      text += '\nSources:\n';
      trailer.sources.forEach((source, i) => {
        text += `${i + 1}. ${source.title} (${source.url})\n`;
      });
    }

    return text;
  }

  /**
   * Create logo element
   */
  createLogo(size = 'medium') {
    const logo = document.createElement('div');
    logo.className = `ai-bradaa-logo logo-size-${size}`;
    logo.innerHTML = `
      <span class="logo-text">${this.brandName}</span>
      <span class="logo-badge">BETA</span>
    `;
    return logo;
  }

  /**
   * Create footer
   */
  createFooter() {
    const footer = document.createElement('footer');
    footer.className = 'ai-bradaa-footer';
    footer.innerHTML = `
      <div class="footer-content">
        <div class="footer-brand">
          <strong>${this.brandName}</strong>
          <span>${this.tagline}</span>
        </div>
        <div class="footer-links">
          <a href="/privacy">Privacy</a>
          <a href="/terms">Terms</a>
          <a href="/about">About</a>
        </div>
        <div class="footer-copyright">
          © ${new Date().getFullYear()} ${this.brandName}. All rights reserved.
        </div>
      </div>
    `;
    return footer;
  }
}

/**
 * Global branding instance
 */
export const branding = new BrandingManager();

export default branding;
